"""Add extracted_text

Revision ID: 7e2403d5f4f5
Revises: f80e667b22fa
Create Date: 2026-07-01 23:11:11.123645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e2403d5f4f5'
down_revision: Union[str, Sequence[str], None] = 'f80e667b22fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('extracted_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'extracted_text')
    # ### end Alembic commands ###
